<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite parallel="methods" name="Failed suite [ActiTIme Batch Execution]">
  <test thread-count="5" parallel="methods" name="LoginFunction(failed)">
    <classes>
      <class name="TestRunnerBlock.LoginRunner">
        <methods>
          <include name="setUpClass"/>
          <include name="runScenario" invocation-numbers="0 1 2 3"/>
          <include name="tearDownClass"/>
        </methods>
      </class> <!-- TestRunnerBlock.LoginRunner -->
    </classes>
  </test> <!-- LoginFunction(failed) -->
  <test thread-count="5" parallel="methods" name="AddNewProject(failed)">
    <classes>
      <class name="TestRunnerBlock.AddNewProject">
        <methods>
          <include name="setUpClass"/>
          <include name="tearDownClass"/>
          <include name="runScenario" invocation-numbers="0"/>
        </methods>
      </class> <!-- TestRunnerBlock.AddNewProject -->
    </classes>
  </test> <!-- AddNewProject(failed) -->
</suite> <!-- Failed suite [ActiTIme Batch Execution] -->
